import {
    IsEmail,
    IsNotEmpty,
    IsOptional,
    IsString,
    MinLength,
    IsIn,
    IsDateString,
    IsArray,
    ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CustomDocumentDto } from '../../common/dto/custom-document.dto';
import { CustomImageDto } from '../../common/dto/custom-image.dto';
import { EducationEntryDto } from '../../common/dto/education-entry.dto';

export class CreateStudentDto {
    // Account
    @IsNotEmpty() @IsString() name: string;
    @IsEmail() email: string;
    @IsString() @MinLength(8) password: string; // Updated to match frontend validation

    // Enrolment
    // rollNumber is auto-generated by backend based on class and section, so it's not required
    @IsOptional()
    rollNumber?: string;

    @IsOptional() @IsString() classId?: string;
    @IsOptional() @IsString() sectionId?: string;
    @IsString() academicYearId: string;
    @IsString() gender: string;

    // ISO date (yyyy-mm-dd)
    @IsDateString() dateOfBirth: string;

    // Student info (optional)
    @IsOptional() @IsString() motherTongue?: string;
    @IsOptional() @IsIn(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']) bloodGroup?: string;
    @IsOptional() @IsString() heightCm?: string;
    @IsOptional() @IsString() weightKg?: string;

    @IsOptional() @IsString() guardianName?: string;
    @IsOptional() @IsString() guardianRelation?: string;

    @IsOptional() @IsString() phone?: string;
    @IsOptional() @IsString() whatsapp?: string;
    @IsOptional() @IsString() address?: string;

    // Father
    @IsOptional() @IsString() fatherName?: string;
    @IsOptional() @IsString() fatherOccupation?: string;
    @IsOptional() @IsString() fatherMonthlyIncome?: string;
    @IsOptional() @IsString() fatherPhone?: string;
    @IsOptional() @IsString() fatherWhatsapp?: string;

    // Mother
    @IsOptional() @IsString() motherName?: string;
    @IsOptional() @IsString() motherOccupation?: string;
    @IsOptional() @IsString() motherMonthlyIncome?: string;
    @IsOptional() @IsString() motherPhone?: string;
    @IsOptional() @IsString() motherWhatsapp?: string;

    // Document URLs (from Cloudinary)
    @IsOptional() @IsString() photoUrl?: string;
    @IsOptional() @IsString() fatherPhotoUrl?: string;
    @IsOptional() @IsString() motherPhotoUrl?: string;
    @IsOptional() @IsString() birthCertificateUrl?: string;
    @IsOptional() @IsString() scstCertificateUrl?: string;
    @IsOptional() @IsString() leavingCertificateUrl?: string;
    @IsOptional() @IsString() vaccineCardUrl?: string;

    // Custom Documents
    @IsOptional()
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => CustomDocumentDto)
    customDocuments?: CustomDocumentDto[];

    // Custom Images
    @IsOptional()
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => CustomImageDto)
    customImages?: CustomImageDto[];

    // Education History
    @IsOptional()
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => EducationEntryDto)
    education?: EducationEntryDto[];
}
